### ISSUE TITLE
Add additional style for the way Markdown editors display Markdown

### ISSUE THREAD

**Issue by bmix** [mrcoles/markdown-css#16]
I am aware, that this is not difficult and that the source is open, I just thought, that would make your project more complete. So it's more a thought, than an issue ;)
![markdownedit](https://cloud.githubusercontent.com/assets/310157/26288612/0b4ed716-3e96-11e7-82d0-df47597dccb1.png)

**Comment by mrcoles** [comment]
Hey @bmix sounds fun. I’m just going to leave it as-is for now. The main goal of this experiment was to create something that looked like valid markdown that could be converted into the actual HTML that was being used, so I didn’t touch alternate coloring or end of line characters, which are not part of the markdown spec.
